### ISSUE TITLE
Tokenizer doesn't install

### ISSUE THREAD

**Issue by dishmal** [colindembovsky/cols-agent-tasks#35]
I installed the package from marketplace and all the build tasks show up except the Tokenizer task.  I've uninstalled and reinstalled with no luck.

**Comment by dishmal** [comment]
I believe the issue is related to another build task I installed from Marketplace which has the same task name and folder structure "Tokenizer" in it.  I see that one in my build list but not this one.  Even after uninstalling both and then re-installing this one, I still can't get it to show up in my options.  Any help would be appreciated.

**Comment by dishmal** [comment]
The other package is this one: ms-devlabs.utilitytasks

**Comment by colindembovsky** [comment]
Hi @dishmal - I'm not sure the name makes a difference since each task has a unique guid. Are you on VSTS or TFS? If TFS, which version?

**Comment by dishmal** [comment]
On-premise TFS 2015 Update 3.

**Comment by omarw** [comment]
I'm experiencing the same problem. This is the only extension I've installed. TFS 2015 Update 3

All other tasks except Tokenizer are available.

**Comment by dishmal** [comment]
I just noticed the extension manifest json file doesn't list Tokenizer in the files list to set up the path:
    "files": [
        {
            "path": "Tasks/AzureWebDeploy"
        },
        {
            "path": "Tasks/DockerPublish"
        },
        {
            "path": "Tasks/ReplaceTokens"
        },
        {
            "path": "Tasks/VersionAssemblies"
        },
        {
            "path": "Tasks/DacPacReport"
        },
        {
            "path": "Tasks/CoverageGate"
        }
    ],

**Comment by colindembovsky** [comment]
Thanks @dishmal I just noticed that! I've fixed the manifest in [this commit](https://github.com/colindembovsky/cols-agent-tasks/commit/64f032f3e1e8303854af109c23ad48862e199bdb) and version 1.1.62 in the marketplace now has the correct manifest. Please let me know if you get the task! (Same for you @omarw)

**Comment by dishmal** [comment]
It now shows up through VSTS and I'll validate it works after the install on my company TFS 2015 install tomorrow at the office, but assuming it will.  Thanks!

**Comment by omarw** [comment]
The tokenizer task shows up for me now but now I'm getting the following error at build time. Any ideas?

2016-12-06T12:51:31.1308775Z Set workingFolder to default: C:\Agent\tasks\JSONTokenizer\1.1.62
2016-12-06T12:51:31.2402570Z module.js:341
2016-12-06T12:51:31.2402570Z     throw err;
2016-12-06T12:51:31.2402570Z     ^
2016-12-06T12:51:31.2402570Z Error: Cannot find module 'vsts-task-lib/task'

**Comment by dishmal** [comment]
Successfully installed on TFS 2015 Update 3 however I get the same error as @omarw

**Comment by dishmal** [comment]
Oops, didn't mean to close it...

**Comment by colindembovsky** [comment]
Dang it - my build definition wasn't restoring the dependencies for the Tokenizer task - it's now fixed and working in 1.1.63!
